export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as CreateProduct} from './CreateProduct'
export {default as Products} from "./Products"
export {default as Profile} from "./Profile"
export {default as HomeFooter} from "./HomeFooter"
export {default as Cart} from "./Cart"
export {default as SeeDetails} from "./SeeDetails"